version: '3.8'
services:
  backend:
    build: .
    container_name: 'votehub-backend'
    ports:
      - '5000:5000'
    environment:
      - MONGO_URL=mongodb://mongo-server:27017/votehub
    depends_on:
      - mongodb
    networks:
      - node-network
  mongodb:
    image: 'mongo:7'
    container_name: 'mongo-server'
    ports:
      - '27017:27017'
    networks:
      - node-network

volumes:
  db-data:

networks:
  node-network:
    driver: bridge
