apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-hub-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-hub
  template:
    metadata:
      labels:
        app: vote-hub
    spec:
      containers:
        - name: vote-hub-server
          image: vote-hub/server:1.0
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: vote-hub-service
spec:
  selector:
    app: vote-hub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
