name: Deployment

on:
  push:
    branches: ["main"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker Login - Azure Container Registry
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        login-server: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}
    
    - name: Build and Push - Azure Container Registry
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/votehub:latest
        docker tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/votehub:latest ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/votehub:$(date +%s)
        docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/votehub
