name: Deployment

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login 
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          login-server: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}

      - name: Build and Push Docker Image
        run: |
          docker-compose build
          docker-compose push

    - name: Deploy with Docker Compose
      run: |
        az webapp config container set --name votehub-server --resource-group GithubActions --multicontainer-config-type compose --multicontainer-config-file docker-compose.yml
